name: ci

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Set up Python 3.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.10"

#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pytest
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#    - name: Test with pytest
#      run: |
#        pytest

    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.44.0
        cache: true
    - run: pixi run pytest
